run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  skip-files:
    - "^zz_generated.*"
  skip-dirs:
    - vendor
    - test

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  fast: false
  disable-all: true
  enable:
    - gofmt
    - govet
    - goimports
    - ineffassign
    - staticcheck
    - misspell
    - vet
    - unconvert

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  misspell:
    locale: US
  staticcheck:
    go: "1.19"
    checks: [
      "all",
      "-ST1000",  # Incorrect or missing package comment
      "-ST1003",  # Poorly chosen identifier
      "-ST1005",  # Incorrectly formatted error string
      "-ST1006",  # Poorly chosen receiver name
      "-ST1012",  # Poorly chosen name for error variable
      "-ST1016",  # Use consistent method receiver names
      "-SA1019",  # Using a deprecated function, variable, constant or field
    ]