{{- if .Values.controllerManager.create }}
{{- if .Values.admissionWebhook.create }}
{{- if false }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ template "nebula-operator.namespace" . }}/{{ template "admission-webhook.name" . }}-cert
  name: {{ template "admission-webhook.name" . }}-mutating
  labels:
  {{- include "admission-webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ template "admission-webhook.name" . }}-service
        namespace: {{ template "nebula-operator.namespace" . }}
        path: /apis/admission.nebula-graph.io/v1alpha1/statefulsetmutating
    failurePolicy: Fail
    name: statefulsetmutating.nebula-graph.io
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - statefulsets
    sideEffects: None
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ template "nebula-operator.namespace" . }}/{{ template "admission-webhook.name" . }}-cert
  name: {{ template "admission-webhook.name" . }}-validating
  labels:
  {{- include "admission-webhook.labels" . | nindent 4 }}
webhooks:
  - name: nebulaclustervalidating.nebula-graph.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ template "admission-webhook.name" . }}-service
        namespace: {{ template "nebula-operator.namespace" . }}
        path: /apis/admission.nebula-graph.io/v1alpha1/nebulaclustervalidating
    failurePolicy: Fail
    rules:
      - apiGroups:
          - apps.nebula-graph.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - nebulaclusters
    sideEffects: None
  - name: statefulsetvalidating.nebula-graph.io
    {{- include "admission-webhook.objectSelector" . | nindent 4 }}
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ template "admission-webhook.name" .}}-service
        namespace: {{ template "nebula-operator.namespace" . }}
        path: /apis/admission.nebula-graph.io/v1alpha1/statefulsetvalidating
    failurePolicy: Fail
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - statefulsets
          - statefulsets/scale
    sideEffects: None
  - name: kruisestatefulsetvalidating.nebula-graph.io
    {{- include "admission-webhook.objectSelector" . | nindent 4 }}
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ template "admission-webhook.name" . }}-service
        namespace: {{ template "nebula-operator.namespace" . }}
        path: /apis/admission.nebula-graph.io/v1alpha1/statefulsetvalidating
    failurePolicy: Fail
    rules:
      - apiGroups:
          - apps.kruise.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - statefulsets
          - statefulsets/scale
    sideEffects: None
{{- end }}
{{- end }}
