{{- if .Values.admissionWebhook.contollerManagerAdmissionWebhook.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "controller-manager-admission-webhook.name" . }}-service
  namespace: {{ template "nebula-operator.namespace" . }}
  labels:
  {{- include "admission-webhook.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
  {{- include "admission-webhook.matchLabels" . | nindent 4 }}
{{- end }}

