{{- if .Values.scheduler.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ template "nebula-operator.namespace" . }}
  labels:
  {{- include "scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      # Compose all plugins in one profile
      - schedulerName: {{ .Values.scheduler.schedulerName }}
        plugins:
          multiPoint:
            enabled:
            {{- range $.Values.scheduler.plugins.enabled }}
              - name: {{ title . }}
            {{- end }}
            disabled:
            {{- range $.Values.scheduler.plugins.disabled }}
              - name: {{ title . }}
            {{- end }}
{{- end }}

