{{- if .Values.scheduler.create }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scheduler.name" . }}-deployment
  namespace: {{ template "nebula-operator.namespace" . }}
  labels:
  {{- include "scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
    {{- include "scheduler.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "scheduler.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "scheduler.name" . }}-sa
      {{- include "nebula-operator.imagePullSecrets" . | indent 6 }}
      containers:
        - name: scheduler
          image: {{ .Values.image.nebulaOperator.image }}
          imagePullPolicy: {{ .Values.image.nebulaOperator.imagePullPolicy }}
          command:
            - /usr/local/bin/scheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --leader-elect
            - --leader-elect-resource-name={{ .Values.scheduler.schedulerName }}
            - --leader-elect-resource-namespace={{ template "nebula-operator.namespace" . }}
            - --v={{ .Values.scheduler.verbosity }}
          {{- if or .Values.kubernetesClusterDomain .Values.scheduler.env }}
          env:
            {{- if .Values.kubernetesClusterDomain }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ .Values.kubernetesClusterDomain }}
            {{- end }}
            {{- if .Values.scheduler.env }}{{ toYaml .Values.scheduler.env | nindent 12 }}{{- end }}
          {{- end }}
          resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 15
          readinessProbe:
              httpGet:
                path: /healthz
                port: 10259
                scheme: HTTPS
          securityContext:
              privileged: false
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
              readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      restartPolicy: Always
{{- end }}

