{{- if .Values.controllerManager.create }}
{{- if .Values.scheduler.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scheduler.name" . }}-sa
  namespace: {{ template "nebula-operator.namespace" . }}
  labels:
  {{- include "scheduler.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "scheduler.name" . }}-role
  labels:
  {{- include "scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - nodes
      - configmaps
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
      - pods/status
      - events
      - endpoints
      - pods/binding
    verbs:
      - get
      - list
      - watch
      - patch
      - delete
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
    verbs:
      - delete
      - get
      - patch
      - update
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - nebula-scheduler
    resources:
      - leases
    verbs:
      - get
      - update
  - apiGroups:
      - "apps.nebula-graph.io"
    resources:
      - nebulaclusters
    verbs:
      - get
      - list
      - delete
      - update
      - create
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - csinodes
      - storageclasses
    verbs:
      - get
      - list
      - delete
      - update
      - create
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - delete
      - update
      - create
      - watch
  - apiGroups:
      - "policy"
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - delete
      - update
      - create
      - watch
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - get
      - list
      - delete
      - update
      - create
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "scheduler.name" . }}-rolebinding
  labels:
  {{- include "scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "scheduler.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "scheduler.name" . }}-sa
    namespace: {{ template "nebula-operator.namespace" . }}
{{- end }}
{{- end }}
