---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nebulacluster
  failurePolicy: Fail
  name: nebulaclustervalidating.nebula-graph.io
  rules:
  - apiGroups:
    - apps.nebula-graph.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nebulaclusters
  sideEffects: None
