apiVersion: v1
entries:
  nebula-cluster:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-07-20T16:38:43.161264382+08:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: aa03c80a212414404e11aa1b026802b86f33063f9eaf2ea484b4195e0d301ecc
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: vee.zhang@vesoft.com
      name: Vee Zhang
    - email: kevin.qiao@vesoft.com
      name: Kevin Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula-graph
    - https://github.com/vesoft-inc/nebula-storage
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://vesoft-inc.github.io/nebula-operator/charts/nebula-cluster-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.8.0
    created: "2021-09-24T11:53:52.508186+08:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: a066917e40d489bfb10396155101bec78ef8f4f6b0c8c5e900149d13af8d91ce
    home: https://nebula-graph.io
    keywords:
      - kubernetes
      - operator
      - nebula-graph
      - database
      - graph database
    maintainers:
      - email: vee.zhang@vesoft.com
        name: Vee Zhang
      - email: kevin.qiao@vesoft.com
        name: Kevin Qiao
    name: nebula-cluster
    sources:
      - https://github.com/vesoft-inc/nebula-graph
      - https://github.com/vesoft-inc/nebula-storage
      - https://github.com/vesoft-inc/nebula-operator
    urls:
      - https://vesoft-inc.github.io/nebula-operator/charts/nebula-cluster-0.8.0.tgz
    version: 0.8.0
  nebula-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-07-20T16:38:43.162192859+08:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: 92ff3f3e6eda554ae4e3bdacdf9b5d95eaf2a2f12ab2d01a0bbc898dcb83fe21
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: vee.zhang@vesoft.com
      name: Vee Zhang
    - email: kevin.qiao@vesoft.com
      name: Kevin Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://vesoft-inc.github.io/nebula-operator/charts/nebula-operator-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.8.0
    created: "2021-09-24T11:53:52.509111+08:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: f45a7a804622614d3401b85f72ccd96955fdf7e4a1dfb1dd56cacda5365330d8
    home: https://nebula-graph.io
    keywords:
      - kubernetes
      - operator
      - nebula-graph
      - database
      - graph database
    maintainers:
      - email: vee.zhang@vesoft.com
        name: Vee Zhang
      - email: kevin.qiao@vesoft.com
        name: Kevin Qiao
    name: nebula-operator
    sources:
      - https://github.com/vesoft-inc/nebula-operator
    urls:
      - https://vesoft-inc.github.io/nebula-operator/charts/nebula-operator-0.8.0.tgz
    version: 0.8.0
generated: "2021-09-24T11:53:52.507102+08:00"
