apiVersion: v1
entries:
  nebula-cluster:
  - apiVersion: v2
    appVersion: 1.8.7
    created: "2026-03-05T23:15:47.285577-08:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: df86428ecb519230dd60813e5ab8d6601986df2fb4892a01c826fd5db8331a9d
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.7/nebula-cluster-1.8.7.tgz
    version: 1.8.7
  - apiVersion: v2
    appVersion: 1.8.6
    created: "2025-09-09T14:51:54.02594-07:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: 962412ff1220e194158623573ac7cabfa88a7f5fd2b689cbacbea837093c8de3
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.6/nebula-cluster-1.8.6.tgz
    version: 1.8.6
  - apiVersion: v2
    appVersion: 1.8.5
    created: "2025-08-12T17:56:00.752953-07:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: 4fab733400cdca05fa9c6d76e77ae7952fd3d8317d913fce950cd190a24e322e
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.5/nebula-cluster-1.8.5.tgz
    version: 1.8.5
  - apiVersion: v2
    appVersion: 1.8.4
    created: "2025-07-16T23:01:31.910325-07:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: b72629cbb0e379d5a6faf1d7deefb3d6340b041e862fcac0259a8c8bb8565f25
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.4/nebula-cluster-1.8.4.tgz
    version: 1.8.4
  - apiVersion: v2
    appVersion: 1.8.3
    created: "2025-07-01T22:17:48.772119-07:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: d9f343b231c6010686579f9107f9c87cb32863f12cd24fae1ef6a881109ec1eb
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.3/nebula-cluster-1.8.3.tgz
    version: 1.8.3
  - apiVersion: v2
    appVersion: 1.8.2
    created: "2025-07-01T22:17:48.771805-07:00"
    description: Nebula Cluster Helm chart for Kubernetes
    digest: 7bbbe622474259747fafcd59125525f849e13c71ba7b847574ec7ad5761190f1
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-cluster
    sources:
    - https://github.com/vesoft-inc/nebula
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.3/nebula-cluster-1.8.2.tgz
    version: 1.8.2
  nebula-operator:
  - apiVersion: v2
    appVersion: 1.8.7
    created: "2026-03-05T23:15:47.295968-08:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: b8c8c2099e14ed14c363045f9fa722a7cefde8ea48e8c73053984b4908a94a31
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.7/nebula-operator-1.8.7.tgz
    version: 1.8.7
  - apiVersion: v2
    appVersion: 1.8.6
    created: "2025-09-09T14:51:54.034002-07:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: 35718ef7aec442bafe9a3fb5ea6d47a288b862cb09ce8d0c29379bf2eb0494f1
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.6/nebula-operator-1.8.6.tgz
    version: 1.8.6
  - apiVersion: v2
    appVersion: 1.8.5
    created: "2025-08-12T17:56:00.758799-07:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: c9c4782d3c61e04ef567fae09839dd1f73a09cecab81244ee3f76b4da9ff152d
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.5/nebula-operator-1.8.5.tgz
    version: 1.8.5
  - apiVersion: v2
    appVersion: 1.8.4
    created: "2025-07-16T23:01:31.914842-07:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: 309f41f036722584a47f53cc812a5cf9fef17e306076d5ca9bcc2791f0b23222
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.4/nebula-operator-1.8.4.tgz
    version: 1.8.4
  - apiVersion: v2
    appVersion: 1.8.3
    created: "2025-07-01T22:17:48.775327-07:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: 79fd28dd6319326061269516bd1347c0e1dcbbf598ff73d8d783c30798510885
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.3/nebula-operator-1.8.3.tgz
    version: 1.8.3
  - apiVersion: v2
    appVersion: 1.8.2
    created: "2025-07-01T22:17:48.774091-07:00"
    description: Nebula Operator Helm chart for Kubernetes
    digest: e055428c6fbe171529c4afe0037aa453a423c2d5fde8b7c25d5b1e78b9fabb6d
    home: https://nebula-graph.io
    keywords:
    - kubernetes
    - operator
    - nebula-graph
    - database
    - graph database
    maintainers:
    - email: kevin.liu@vesoft.com
      name: Kevin Liu
    - email: kevin.qiao@vesoft.com
      name: Lei Qiao
    name: nebula-operator
    sources:
    - https://github.com/vesoft-inc/nebula-operator
    urls:
    - https://github.com/vesoft-inc/nebula-operator/releases/download/v1.8.3/nebula-operator-1.8.2.tgz
    version: 1.8.2
generated: "2025-07-01T22:17:48.771031-07:00"
