apiVersion: batch/v1
kind: Job
metadata:
  name: nebula-full-backup
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: nebula-image
      containers:
        - image: reg.vesoft-inc.com/cloud-dev/br-ent:v3.5.1
          imagePullPolicy: Always
          name: backup
          command:
            - /bin/sh
            - -ecx
            - 'exec /usr/local/bin/br-ent backup full 
            --meta META_ADDRESS:9559 
            --storage s3://BUCKET
            --s3.access_key ACCESS_KEY 
            --s3.secret_key SECRET_KEY 
            --s3.region REGION 
            --s3.endpoint https://s3.REGION.amazonaws.com
            --enable_ssl
            --insecure_skip_verify'
          volumeMounts:
            - mountPath: /usr/local/certs/client.crt
              name: client-crt
              subPath: client.crt
            - mountPath: /usr/local/certs/client.key
              name: client-key
              subPath: client.key
            - mountPath: /usr/local/certs/ca.crt
              name: ca-crt
              subPath: ca.crt
      volumes:
        - name: client-crt
          secret:
            defaultMode: 420
            items:
              - key: tls.crt
                path: client.crt
            secretName: client-cert
        - name: client-key
          secret:
            defaultMode: 420
            items:
              - key: tls.key
                path: client.key
            secretName: client-cert
        - name: ca-crt
          secret:
            defaultMode: 420
            items:
              - key: root.crt
                path: ca.crt
            secretName: ca-cert
