apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
type: Opaque
data:
  access-key: <ACCESS_KEY>
  secret-key: <SECRET_KEY>
---
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaScheduledBackup
metadata:
  name: backup1
spec:
  backupTemplate:
    toolImage: reg.vesoft-inc.com/cloud-dev/br-ent:v3.5.1
    br:
      clusterName: nebula-kevinl
      s3:
        region: "us-west-2"
        bucket: "nebula-br-test"
        endpoint: "https://s3.us-west-2.amazonaws.com"
        secretName: "aws-s3-secret"
  schedule: "*/5 * * * *"
  maxBackups: 7
