apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  access_key: <ACCESS_KEY>
  secret_key: <SECRET_KEY>
---
apiVersion: v1
kind: Pod
metadata:
  name: nebula-restore
spec:
  imagePullSecrets:
    - name: nebula-image
  containers:
    - image: reg.vesoft-inc.com/cloud-dev/br-ent:v3.7.0
      imagePullPolicy: Always
      name: restore
      command:
        - /bin/sh
        - -ecx
        - 'exec /usr/local/bin/br-ent restore full 
        --mode=k8s --cluster=nebula 
        --namespace default 
        --secret=aws-secret 
        --name BACKUP_2023_02_10_09_57_17 
        --storage s3://BUCKET 
        --s3.region=REGION 
        --s3.endpoint https://s3.REGION.amazonaws.com'