apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
type: Opaque
data:
  access-key: QVNJQVE0WFlSWFE1TlhVMlczNlUK
  secret-key: ZFJ6OEdNcDdxenMwVGFGdExVM2RpYkk4b2hHRWRSamgvNTdzWkg3Ugo=
---
apiVersion: v1
kind: Pod
metadata:
  name: nebula-restore
spec:
  containers:
    - image: vesoft/br-ent:v3.4.0
      imagePullPolicy: Always
      name: restore
      command:
        - /bin/sh
        - -ecx
        - exec /usr/local/bin/nebula-br restore full
        - --mode=k8s
        - --cluster=nebula
        - --namespace default
        - --secret=aws-s3-secret
        - --name BACKUP_2023_02_10_09_57_17
        - --storage s3://$BUCKET/
        - --s3.region=$REGION
        - --s3.endpoint https://s3.$REGION.amazonaws.com