apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: {{ template "nebula-cluster.name" . }}
  namespace: {{ template "nebula-cluster.namespace" . }}
  labels:
    {{ include "nebula-cluster.labels" . | indent 4 }}
spec:
  graphd:
    replicas: {{ .Values.nebula.graphd.replicas }}
    resources: {{ toYaml .Values.nebula.graphd.resources | nindent 6 }}
    image: {{ .Values.nebula.graphd.image }}
    version: {{ .Values.nebula.version }}
    {{- with .Values.nebula.graphd.env }}
    env:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.config }}
    config:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    service:
      type: {{ .Values.nebula.graphd.serviceType }}
      externalTrafficPolicy: Local
    {{- if .Values.nebula.graphd.logVolume.enable }}
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.graphd.logVolume.storage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    {{- end }}
    {{- with .Values.nebula.graphd.podLabels }}
    labels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.podAnnotations }}
    annotations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.livenessProbe }}
    livenessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.volumes }}
    volumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.volumeMounts }}
    volumeMounts:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  metad:
    replicas: {{ .Values.nebula.metad.replicas }}
    resources: {{ toYaml .Values.nebula.metad.resources | nindent 6 }}
    image: {{ .Values.nebula.metad.image }}
    version: {{ .Values.nebula.version }}
    {{- if .Values.nebula.metad.licenseManagerURL }}
    licenseManagerURL: {{ .Values.nebula.metad.licenseManagerURL }}
    {{- end }}
    {{- with .Values.nebula.metad.env }}
    env:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.config }}
    config:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.metad.logVolume.storage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    dataVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.metad.dataVolume.storage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    {{- with .Values.nebula.metad.podLabels }}
    labels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.podAnnotations }}
    annotations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.license }}
    license:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.livenessProbe }}
    livenessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.volumes }}
    volumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.volumeMounts }}
    volumeMounts:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  storaged:
    replicas: {{ .Values.nebula.storaged.replicas }}
    resources: {{ toYaml .Values.nebula.storaged.resources | nindent 6 }}
    image: {{ .Values.nebula.storaged.image }}
    version: {{ .Values.nebula.version }}
    enableAutoBalance: {{ .Values.nebula.storaged.enableAutoBalance }}
    enableForceUpdate: {{ .Values.nebula.enableForceUpdate }}
    {{- with .Values.nebula.storaged.env }}
    env:
    {{ toYaml | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.config }}
    config:
    {{ toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.nebula.storaged.logVolume.enable }}
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.storaged.logVolume.storage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    {{- end }}
    dataVolumeClaims:
    {{- range $volume := .Values.nebula.storaged.dataVolumes }}
    - resources:
        requests:
          storage: {{ $volume.storage }}
      {{- if $.Values.nebula.storageClassName }}
      storageClassName: {{ $.Values.nebula.storageClassName }}
      {{- end }}
    {{- end }}
    {{- with .Values.nebula.storaged.podLabels }}
    labels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.podAnnotations }}
    annotations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.livenessProbe }}
    livenessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.volumes }}
    volumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.volumeMounts }}
    volumeMounts:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  exporter:
    replicas: {{ .Values.nebula.exporter.replicas }}
    resources: {{ toYaml .Values.nebula.exporter.resources | nindent 6 }}
    image: {{ .Values.nebula.exporter.image }}
    version: {{ .Values.nebula.exporter.version }}
    {{- with .Values.nebula.exporter.env }}
    env:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.podLabels }}
    labels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.podAnnotations }}
    annotations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.livenessProbe }}
    livenessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.volumes }}
    volumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.exporter.volumeMounts }}
    volumeMounts:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    maxRequests: {{ .Values.nebula.exporter.maxRequests }}
  agent:
    image: {{ .Values.nebula.agent.image }}
    version: {{ .Values.nebula.agent.version }}
    resources: {{ toYaml .Values.nebula.agent.resources | nindent 6 }}
  console:
    username: {{ .Values.nebula.console.username }}
    password: {{ .Values.nebula.console.password }}
    image: {{ .Values.nebula.console.image }}
    version: {{ .Values.nebula.console.version }}
    {{- with .Values.nebula.console.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  reference: {{ toYaml .Values.nebula.reference | nindent 4 }}
  imagePullPolicy: {{ .Values.nebula.imagePullPolicy }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  schedulerName: {{ .Values.nebula.schedulerName }}
  topologySpreadConstraints: {{ toYaml .Values.nebula.topologySpreadConstraints | nindent 4 }}
  enablePVReclaim: {{ .Values.nebula.enablePVReclaim }}
  enableBR: {{ .Values.nebula.enableBR }}
  {{- with .Values.nebula.logRotate }}
  logRotate:
  {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.nebula.alpineImage }}
  alpineImage: {{ .Values.nebula.alpineImage }}
  {{- end }}
