apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: {{ template "nebula-cluster.name" . }}
  namespace: {{ template "nebula-cluster.namespace" . }}
  labels:
    {{ include "nebula-cluster.labels" . | indent 4 }}
spec:
  graphd:
    replicas: {{ .Values.nebula.graphd.replicas }}
    resources: {{ toYaml .Values.nebula.graphd.resources | nindent 6 }}
    image: {{ .Values.nebula.graphd.image }}
    version: {{ .Values.nebula.version }}
    env: {{ toYaml .Values.nebula.graphd.env | nindent 6 }}
    config: {{ toYaml .Values.nebula.graphd.config | nindent 6 }}
    service:
      type: {{ .Values.nebula.graphd.serviceType }}
      externalTrafficPolicy: Local
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.graphd.logStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    labels: {{ toYaml .Values.nebula.graphd.podLabels | nindent 6 }}
    annotations: {{ toYaml .Values.nebula.graphd.podAnnotations | nindent 6 }}
    {{- with .Values.nebula.graphd.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.graphd.sidecarVolumes }}
    sidecarVolumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  metad:
    replicas: {{ .Values.nebula.metad.replicas }}
    resources: {{ toYaml .Values.nebula.metad.resources | nindent 6 }}
    image: {{ .Values.nebula.metad.image }}
    version: {{ .Values.nebula.version }}
    env: {{ toYaml .Values.nebula.metad.env | nindent 6 }}
    config: {{ toYaml .Values.nebula.metad.config | nindent 6 }}
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.metad.logStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    dataVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.metad.dataStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    labels: {{ toYaml .Values.nebula.metad.podLabels | nindent 6 }}
    annotations: {{ toYaml .Values.nebula.metad.podAnnotations | nindent 6 }}
    {{- with .Values.nebula.metad.license }}
    license:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.metad.sidecarVolumes }}
    sidecarVolumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  storaged:
    replicas: {{ .Values.nebula.storaged.replicas }}
    resources: {{ toYaml .Values.nebula.storaged.resources | nindent 6 }}
    image: {{ .Values.nebula.storaged.image }}
    version: {{ .Values.nebula.version }}
    enableAutoBalance: {{ .Values.nebula.storaged.enableAutoBalance }}
    enableForceUpdate: {{ .Values.nebula.enableForceUpdate }}
    env: {{ toYaml .Values.nebula.storaged.env | nindent 6 }}
    config: {{ toYaml .Values.nebula.storaged.config | nindent 6 }}
    logVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.nebula.storaged.logStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    dataVolumeClaims:
    - resources:
        requests:
          storage: {{ .Values.nebula.storaged.dataStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
    labels: {{ toYaml .Values.nebula.storaged.podLabels | nindent 6 }}
    annotations: {{ toYaml .Values.nebula.storaged.podAnnotations | nindent 6 }}
    {{- with .Values.nebula.storaged.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.affinity }}
    affinity:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.tolerations }}
    tolerations:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.readinessProbe }}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.initContainers }}
    initContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.sidecarContainers }}
    sidecarContainers:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nebula.storaged.sidecarVolumes }}
    sidecarVolumes:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  reference: {{ toYaml .Values.nebula.reference | nindent 4 }}
  imagePullPolicy: {{ .Values.nebula.imagePullPolicy }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 4 }}
  {{- end }}
  schedulerName: {{ .Values.nebula.schedulerName }}
  unsatisfiableAction: {{ .Values.nebula.unsatisfiableAction }}
  enablePVReclaim: {{ .Values.nebula.enablePVReclaim }}
  enableBR: {{ .Values.nebula.enableBR }}

