{{- range $component, $pdb-settings := .Values.pdb }}
  {{- $enabled := index $pdb-settings "enable" }}
  {{- $minAvailable := index $pdb-settings "minAvailable" }}
  {{- $maxUnavailable := index $pdb-settings "maxUnavailable" }}
  {{- if $enabled }}
  apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    name: {{ template "nebula-cluster.name" . }}-{{ $component }}-pdb
  spec:
    {{- if gt (int $minAvailable) 0 }}
    minAvailable: {{ $minAvailable }}
    {{- else if ge (int $maxUnavailable) 0 }}
    maxUnavailable: {{ $maxUnavailable }}
    {{- else }}
    {{- fail "either minAvailable or maxUnavailable for the $component pdb must be specified. \
    minAvailable must be a positive integer and maxUnavailable must be a non-negative integer." }}
    {{- end }}
    selector:
      matchLabels:
        app.kubernetes.io/cluster: {{ template "nebula-cluster.name" . }}
        app.kubernetes.io/component: {{ $component }}
  {{- end }}
{{- end }}